name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Compute base-href
        id: basehref
        shell: bash
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [[ "$REPO_NAME" == "$OWNER.github.io" ]]; then
            echo "BASE_HREF=/" >> $GITHUB_ENV
          else
            echo "BASE_HREF=/$REPO_NAME/" >> $GITHUB_ENV
          fi
          echo "Using BASE_HREF=$BASE_HREF"

      - name: Build web
        run: |
          flutter build web \
            --release \
            --base-href "$BASE_HREF" \
            --dart-define=ENABLE_FIREBASE_WEB=${{ vars.ENABLE_FIREBASE_WEB || 'false' }} \
            --dart-define=FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY || secrets.FIREBASE_API_KEY || '' }} \
            --dart-define=FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID || secrets.FIREBASE_APP_ID || '' }} \
            --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID || secrets.FIREBASE_MESSAGING_SENDER_ID || '' }} \
            --dart-define=FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID || secrets.FIREBASE_PROJECT_ID || '' }} \
            --dart-define=FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN || '' }} \
            --dart-define=FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET || '' }} \
            --dart-define=FIREBASE_MEASUREMENT_ID=${{ vars.FIREBASE_MEASUREMENT_ID || '' }} \
            --dart-define=FIREBASE_RECAPTCHA_KEY=${{ vars.FIREBASE_RECAPTCHA_KEY || secrets.FIREBASE_RECAPTCHA_KEY || '' }}
      - name: Add 404 fallback (Pages refresh fix)
        run: |
          cp build/web/index.html build/web/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
